version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@storybook/addon-a11y"
    versions:
    - 6.1.21
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.5
    - 6.2.7
    - 6.2.8
  - dependency-name: gatsby
    versions:
    - 3.2.1
    - 3.3.0
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: stylelint
    versions:
    - 13.12.0
  - dependency-name: "@types/jest"
    versions:
    - 26.0.22
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.19
    - 6.1.20
    - 6.1.21
    - 6.2.1
    - 6.2.2
    - 6.2.3
  - dependency-name: sharp
    versions:
    - 0.27.1
    - 0.28.0
  - dependency-name: gatsby-link
    versions:
    - 3.0.1
    - 3.1.0
    - 3.2.0
  - dependency-name: "@storybook/addon-docs"
    versions:
    - 6.1.20
    - 6.1.21
  - dependency-name: netlify-cli
    versions:
    - 3.10.9
    - 3.8.5
    - 3.8.6
    - 3.9.0
